#!/usr/bin/env bash

SED_PATH="/usr/local/opt/gnu-sed/libexec/gnubin/sed"

if [ $(which sed) != "${SED_PATH}" ]; then
  echo "The GNU version of 'sed' is not installed"
  echo "To install on OS X use 'brew install gnu-sed'"

  exit 1
fi

DIRS="apps bin config"
FILES="DEVELOPMENT.md Dockerfile docker-compose.yml LICENSE.txt README.md mix.exs mix.lock .env .env.demo .env.example .env.travis .dockerignore .travis.yml"

capitalize() {
  FIRST=$(echo ${1:0:1} | tr '[:lower:]' '[:upper:]')

  echo ${FIRST}${1:1}
}

uppercase() {
  echo ${1} | tr a-z A-Z
}

lowercase() {
  echo ${1} | tr A-Z a-z
}

replace() {
  find ${DIRS} ${FILES} -type f -not -path '*node_modules*' | xargs ${SED_PATH} -i'' -e "s/${1}/${2}/g"
}

move() {
  find ${DIRS} -type d | grep "${1}" | while read DIR ; do
    NEW_DIR=`echo ${DIR} | ${SED_PATH} -e "s/${1}/${2}/g"`
    mv -n "${DIR}/" "${NEW_DIR}"
  done

  find ${DIRS} -type f | grep "${1}" | while read FILE ; do
    NEW_FILE=`echo ${FILE} | ${SED_PATH} -e "s/${1}/${2}/g"`
    mv "${FILE}" "${NEW_FILE}"
  done
}

move $1 $2
move $(capitalize $1) $(capitalize $2)
move $(uppercase $1) $(uppercase $2)
move $(lowercase $1) $(lowercase $2)

replace $1 $2
replace $(capitalize $1) $(capitalize $2)
replace $(uppercase $1) $(uppercase $2)
replace $(lowercase $1) $(lowercase $2)
